#!/bin/bash
# Automated AWS Bedrock Setup Script

echo "🚀 AWS Bedrock Setup for Paper Analyzer"
echo "========================================"
echo ""

# Check if Terraform is installed
if ! command -v terraform &> /dev/null; then
    echo "❌ Terraform not found!"
    echo "Install it with: brew install terraform"
    exit 1
fi

echo "✅ Terraform found"
echo ""

# Check AWS CLI
if ! command -v aws &> /dev/null; then
    echo "⚠️  AWS CLI not found (optional but recommended)"
    echo "Install it with: brew install awscli"
else
    echo "✅ AWS CLI found"
fi

echo ""
echo "📋 This script will:"
echo "  1. Initialize Terraform"
echo "  2. Create IAM user with Bedrock permissions"
echo "  3. Generate access keys"
echo "  4. Update backend/.env with credentials"
echo ""
read -p "Continue? (y/n) " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Aborted"
    exit 1
fi

# Navigate to terraform directory
cd terraform || exit 1

echo ""
echo "🔧 Initializing Terraform..."
terraform init

echo ""
echo "📝 Planning infrastructure..."
terraform plan

echo ""
read -p "Apply this configuration? (y/n) " -n 1 -r
echo ""

if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "❌ Aborted"
    exit 1
fi

echo ""
echo "🚀 Applying Terraform configuration..."
terraform apply -auto-approve

if [ $? -ne 0 ]; then
    echo "❌ Terraform apply failed!"
    exit 1
fi

echo ""
echo "✅ Terraform applied successfully!"
echo ""

# Get credentials
ACCESS_KEY=$(terraform output -raw bedrock_access_key_id)
SECRET_KEY=$(terraform output -raw bedrock_secret_access_key)

echo "📝 Updating backend/.env with credentials..."

# Update backend/.env
cd ../backend || exit 1

# Backup existing .env if it exists
if [ -f .env ]; then
    cp .env .env.backup
    echo "✅ Backed up existing .env to .env.backup"
fi

# Create new .env with Terraform outputs
cat > .env << ENVEOF
# AWS Configuration (Auto-generated by Terraform)
AWS_ACCESS_KEY_ID=$ACCESS_KEY
AWS_SECRET_ACCESS_KEY=$SECRET_KEY
AWS_REGION=us-east-1

# AWS Bedrock Model
BEDROCK_MODEL_ID=deepseek-ai.deepseek-v3
BEDROCK_MODEL_TEMPERATURE=0.1
BEDROCK_MAX_TOKENS=4096

# Application Settings
DEBUG=true
LOG_LEVEL=INFO
API_PORT=8734

# CORS Settings
ALLOWED_ORIGINS=http://localhost:3847,http://localhost:3000

# Data Directories
UPLOAD_DIR=data/uploads
EXTRACTED_DIR=data/extracted
ENVEOF

echo "✅ backend/.env updated with AWS credentials"
echo ""

echo "============================================"
echo "✅ AWS SETUP COMPLETE!"
echo "============================================"
echo ""
echo "⚠️  IMPORTANT NEXT STEP:"
echo ""
echo "1. Go to AWS Console:"
echo "   https://console.aws.amazon.com/bedrock"
echo ""
echo "2. Click 'Model Access' in left sidebar"
echo ""
echo "3. Click 'Manage model access'"
echo ""
echo "4. Enable DeepSeek models (or Claude/other models)"
echo ""
echo "5. Click 'Save changes' and wait for approval"
echo ""
echo "6. Restart the backend:"
echo "   cd backend"
echo "   kill \$(cat backend.pid)"
echo "   source venv/bin/activate"
echo "   python -m uvicorn api.app:app --host 0.0.0.0 --port 8734 &"
echo ""
echo "============================================"
echo ""
echo "Your credentials:"
echo "AWS_ACCESS_KEY_ID=$ACCESS_KEY"
echo "AWS_SECRET_ACCESS_KEY=****** (saved to .env)"
echo ""
